### PR TITLE
Create NeutralLossGroups

### PR DESCRIPTION
**Pull request by henryhlam**

### CODE REVIEW

**Review by edeutsch — CHANGES_REQUESTED** [review]
Looks fine to me, except can you make the file extension .md so that the GitHub tooling recognizes it as markdown?

**Comment by mobiusklein** [comment]
I've fixed the file name and added a few more monosaccharides.

This is fine for now. I'll add a JSON file mirroring the isobaric labels to be machine readable.

For guidelines, are we looking to make any labile modification a viable name here, or are there rules about how large/small the components should be?

**Review by mobiusklein — APPROVED** [review]

**Review by edeutsch — APPROVED** [review]

**Comment by henryhlam** [comment]
Yes, I'd say we should define as many as we can think of, e.g. possible glycan losses.

I don't think we have any rule about how complex the neutral loss needs to be. We already define some simple ones in the Peak Annotation Spec, and I'd expect most people will use those. We also don't prohibit people from calling [Hex] "C6H12O6" instead. It's just a matter of readability, in my understanding.

Maybe we can have a rule-of-thumb that if the chemical formula is long enough that it can conceivably map to many possible functional groups, then we use this complex group mechanism to be more specific? For example, there is no point of making a [Water] tag because H2O is already clear and unambiguous.

**Comment by edeutsch** [comment]
Put something like this into the top of the file:

 if the chemical formula is long enough that it can conceivably map to many possible functional groups, then we use this complex group mechanism to be more specific.  For example, there is no point of making a [Water] tag because H2O is already clear and unambiguous.

**Review by mobiusklein — APPROVED** [review]

**Review by edeutsch — APPROVED** [review]

**Pull request merged**
