### PR TITLE
Add railroad diagram for formal grammar

### PR DESCRIPTION
**Pull request by mobiusklein**
Adds a formal grammar railroad diagram for the peptide peak annotation grammar

### CODE REVIEW

**Review by bittremieux — APPROVED** [review]

**Review by edeutsch — APPROVED** [review]
Seems fine, but I can't figure out how to render the HTML in GitHub in my browser. Anyone know? It only shows up as source.

**Comment by bittremieux** [comment]
Yes, I don't think the HTML can directly render from GitHub like that.

**Comment by edeutsch** [comment]
TODO: Joshua will convert the HTML to a .md file

**Comment by mobiusklein** [comment]
To make Markdown work, I'll need to save each SVG separately, or just convert to PDF before uploading. I prefer the former over the latter, but it will just be a bit more work.

**Pull request merged**
